---
################################################################################################
#
# Installation of alacritty
#
################################################################################################
- name: Install required packages for alacritty.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - xterm
    - alacritty
    - alacritty-terminfo
  tags:
    - terminal
    - package

################################################################################################
#
# Configuration of alacritty
#
################################################################################################
- name: Copy xresources file for xterm.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 40-XTerm.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/xresources/40-XTerm"
  notify:
    - compile xresources
  tags:
    - terminal
    - config

- name: Create config directory of alacritty.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/alacritty"
  tags:
    - terminal
    - config
    - directory

- name: Copy alacritty config file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: alacritty.yml.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/alacritty/alacritty.yml"
  tags:
    - terminal
    - config

- name: Copy hotkey file for alacritty and xterm.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 30-xterm.hotkey.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d/30-xterm"
    - src: 40-alacritty.hotkey.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d/40-alacritty"
  notify:
    - compile hotkeys
  tags:
    - terminal
    - config
