---
################################################################################################
#
# Installation of rxvt-unicode and guake
#
################################################################################################
- name: Install required packages.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - rxvt-unicode
  tags:
    - terminal
    - package


################################################################################################
#
# Configuration of rxvt xterm and guake
#
################################################################################################

# xterm and urxvt configs are copied to xresources folder to be compiled into
# one Xresources file. Check md_xserver/handlers/main.yml.
- name: Copy config files for rxvt xterm and guake.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: 40-XTerm
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/xresources/40-XTerm"
    - src: 50-URxvt
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/xresources/50-URxvt"
  notify:
    - compile xresources
  tags:
    - terminal
    - config
