---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for file manager.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - pcmanfm-qt
    state: latest
  tags:
    - file_manager
    - package
