---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for file manager.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - dolphin
  tags:
    - file_manager
    - package
