---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install dependency packages for polybar.
  become: yes
  become_user: "{{ ma_user.name }}"
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    # gtk theme
    - adapta-gtk-theme
    # matching qt5 style
    - kvantum-theme-adapta
    # papirus icon theme
    - papirus-icon-theme
  tags:
    - theme
    - package
    - dependency

####################################################################################################
#
# Configuration of themes
#
####################################################################################################
