---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for theme.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      # gtk theme
      - adapta-gtk-theme
      # qt5 theme engines
      - kvantum-qt5
      # matching qt5 style
      - kvantum-theme-adapta
      # papirus icon theme
      - papirus-icon-theme
      # gtk2 theme engine
      - gtk-engine-murrine
    state: latest
  tags:
    - theme
    - package
    - dependency

####################################################################################################
#
# Configuration of themes
#
####################################################################################################
- name: Create required directories for theme configuration.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/gtk-3.0"
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt"
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/Kvantum"
  tags:
    - theme
    - config
    - directory

- name: Copy theme config files.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: .gtkrc-2.0
      dest: "{{ user.dirs.home }}/.gtkrc-2.0"
    - src: settings.ini
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/gtk-3.0/settings.ini"
    - src: lxqt.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/lxqt.conf"
    - src: kvantum.kvconfig
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/Kvantum/kvantum.kvconfig"
  tags:
    - theme
    - config

- name: Copy theme session config.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
    mode: 0755
  with_items:
    - src: 30-gtk.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d/30-gtk.conf"
  notify:
    - compile session
  tags:
    - theme
    - config

