---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for pulseaudio.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - pulseaudio
    - pulseaudio-alsa
  tags:
    - audio
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Copy audio hotkey file.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: 20-audio
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc.d/20-audio"
  tags:
    - audio
    - hotkey
