---
################################################################################################
#
# Installation of dunst
#
################################################################################################
- name: Install required packages for dunst.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - dunst
  tags:
    - notification
    - package


################################################################################################
#
# Configuration
#
################################################################################################
- name: Create config directory of dunst.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/dunst"
  tags:
    - notification
    - config
    - directory

# Modify file directly if you want to customize dunst
- name: Copy dunst config file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: dunstrc.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/dunst/dunstrc"
  tags:
    - notification
    - config
