---
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for emacs.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - emacs
  tags:
    - text_editor
    - package

################################################################################################
#
# Configuration
#
################################################################################################
- name: Install spacemacs.
  become: yes
  become_user: "{{ ma_user.name }}"
  become_method: sudo
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ma_user.dirs.home }}/.emacs.d"
  tags:
    - text_editor
    - config
