---
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for Sublime Text 3.
  become: yes
  become_user: "{{ aur_user.name }}"
  become_method: sudo
  aur:
    name: "{{ item }}"
    skip_installed: yes
  with_items:
    - sublime-text-dev
  tags:
    - text_editor
    - package

################################################################################################
#
# Configuration
#
################################################################################################
