---
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for firefox.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - firefox
  tags:
    - browser
    - package


################################################################################################
#
# Configuration
#
################################################################################################

# I think it would too complex to configure firefox with files and stuff only
# You usually login to your account to get your settings synchronized etc.
# I do not think I can login and trigger sync using command line (?)
