---
####################################################################################################
#
# Handlers for hotkey daemon
#
####################################################################################################
- name: compile hotkeys
  become: yes
  become_user: root
  become_method: sudo
  assemble:
    src: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc.d"
    dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  tags:
    - hotkey
    - config
