---
####################################################################################################
#
# Handlers for hotkey daemon
#
####################################################################################################
- name: compile hotkeys
  become: yes
  become_user: root
  become_method: sudo
  assemble:
    src: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d"
    dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  tags:
    - hotkey
    - config
