---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for enlighten.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      # enlighten-git does not specify this as a build dependency even though it is
      - ptyhon-sphinx
    state: latest
  tags:
    - backlight
    - package

- name: Install required packages for enlighten.
  become: yes
  become_user: "{{ aur_user.name }}"
  become_method: sudo
  aur:
    name: "{{ item }}"
    skip_installed: yes
  with_items:
    - enlighten-git
  tags:
    - backlight
    - package

####################################################################################################
#
# Configuration of enlighten
#
####################################################################################################
- name: Add user to video group
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user.name }}"
    append: yes
    groups: video
  tags:
    - backlight
    - config

- name: Copy backlight hotkey file.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 21-backlight
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d/21-backlight"
  notify:
    - compile hotkeys
  tags:
    - backlight
    - hotkey
