
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for virtualbox guest utils.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualbox-guest-modules-arch
    - virtualbox-guest-utils
  when: "ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'virtualbox'"
  tags:
    - vbox_guest
    - package

####################################################################################################
#
# Enable
#
####################################################################################################
- name: Enable virtualbox kernel modules.
  become: yes
  become_user: root
  become_method: sudo
  systemd:
    name: vboxservice
    enabled: yes
  when: "ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'virtualbox'"
  tags:
    - dm
    - service

####################################################################################################
#
# Autostart
#
####################################################################################################
- name: Copy desktop files for autostart.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: VBoxClient.desktop
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/autostart/VBoxClient.desktop"
    - src: SwapAltWin.desktop
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/autostart/SwapAltWin.desktop"
  tags:
    - hotkey
    - autostart
