
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for virtualbox guest utils.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualbox-guest-modules-arch
    - virtualbox-guest-utils
  when: "ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'virtualbox'"
  tags:
    - vbox_guest
    - package
