---
################################################################################################
#
# Installation
#
################################################################################################
- name: Install required packages for thunderbird.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - thunderbird
    state: latest
  tags:
    - email_client
    - package


################################################################################################
#
# Configuration
#
################################################################################################
- name: Copy desktop file for launching.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: thunderbird.desktop
      dest: "{{ user.dirs.home }}/{{ user.dirs.share }}/applications/thunderbird.desktop"
  tags:
    - email_client
    - config
    - desktop
