---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for nodejs development.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - nodejs
      - yarn
    state: latest
  tags:
    - dev-nodejs
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Copy yarn global bin config file.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 90-yarn-global-bin.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d/90-yarn-global-bin.conf"
  notify:
    - compile session
  tags:
    - dev-nodejs
    - config
