---
####################################################################################################
#
# Installation of rofi
#
####################################################################################################
- name: Install required packages for rofi.
  become: yes
  become_user: "{{ aur_user.name }}"
  become_method: sudo
  aur:
    name: "{{ item }}"
    skip_installed: yes
  with_items:
    - rofi-git
  tags:
    - runner
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create config directory of rofi.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/rofi"
  tags:
    - runner
    - config
    - directory

- name: Copy theme for rofi.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: custom.rasi.j2
      dest: "{{ user.dirs.home}}/{{ user.dirs.config }}/rofi/custom.rasi"
  tags:
    - runner
    - config

- name: Copy hotkey file for rofi.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 41-rofi.hotkey.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d/41-rofi"
  notify:
    - compile hotkeys
  tags:
    - runner
    - config
