---
####################################################################################################
#
# Installation of rofi
#
####################################################################################################
- name: Install required packages for rofi.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - rofi
  tags:
    - runner
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create config directory of rofi.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/rofi"
  tags:
    - runner
    - config
    - directory

- name: Download theme for rofi.
  become: yes
  become_user: root
  become_method: sudo
  get_url:
    url: https://raw.githubusercontent.com/DaveDavenport/rofi-themes/master/Official%20Themes/solarized_alternate.rasi
    dest: "{{ ma_user.dirs.home}}/{{ ma_user.dirs.config }}/rofi/solarized_alternate.rasi"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  tags:
    - runner
    - config

- name: Copy hotkey file for rofi.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: 41-rofi
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc.d/41-rofi"
  notify:
    - compile xresources
  tags:
    - terminal
    - config
