---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for i3lock.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - i3lock
    state: latest
  tags:
    - screensaver
    - package

####################################################################################################
#
# Hotkey
#
####################################################################################################
- name: Copy i3lock hotkey file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 45-i3lock.hotkey.j2
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/sxhkd/sxhkdrc.d/45-i3lock"
  notify:
    - compile hotkeys
  tags:
    - screensaver
    - hotkey
