---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for lxqt.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - lxqt-config
      - lxqt-policykit
      - lxqt-qtplugin
      - lxqt-session
      - lxqt-sudo
      # here because it manages desktop
      - pcmanfm-qt
    state: latest
  tags:
    - de
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
