---
####################################################################################################
#
# Handlers for session
#
####################################################################################################
- name: compile session
  become: yes
  become_user: root
  become_method: sudo
  assemble:
    src: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d"
    dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  tags:
    - session
    - config
