---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for fish.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - fish
    state: latest
  tags:
    - font
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create fish functions directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/fish/functions"
  tags:
    - shell
    - config

- name: Copy fish function files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: ssh.fish
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/fish/functions/ssh.fish"
  tags:
    - shell
    - config

# this is straight pulling stuff from web without verification
# @TODO: find a better way for this
- name: add fundle for fish plugin management
  become: yes
  become_user: root
  become_method: sudo
  get_url:
    url: https://git.io/fundle
    dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/fish/functions/fundle.fish"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  tags:
    - shell
    - config
    - fundle

- name: Copy fish config files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: config.fish
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/fish/config.fish"
  notify:
    - update fisher packages
  tags:
    - shell
    - config
    - fundle
