---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for fish.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - fish
  tags:
    - font
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create fish functions directory
  become: yes
  become_user: root
  become_method: sudo
  file: 
    path: "{{ item }}"
    state: directory
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/fish/functions"
  tags:
    - shell
    - config

# this is straight pulling stuff from web without verification
# @TODO: find a better way for this
- name: add fundle for fish plugin management
  become: yes
  become_user: root
  become_method: sudo
  get_url:
    url: https://git.io/fundle
    dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/fish/functions/fundle.fish"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  tags:
    - shell
    - config
    - fundle

- name: Copy fish config files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: config.fish
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/fish/config.fish"
  notify:
    - update fisher packages
  tags:
    - shell
    - config
    - fundle
