#!/usr/bin/env bash

# set up workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# others
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

