---
####################################################################################################
#
# Create the account that will use this computer as a user.
#
####################################################################################################
- name: Create normal user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    home: "{{ user.dirs.home }}"
    shell: /bin/bash
  tags:
    - user

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Give this user sudo access for a few commands.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    # can only use shutdown and reboot
    content: "{{ user.name }} ALL=(root) NOPASSWD: {{ user.sudo_commands|join(',') }}\n"
    dest: "/etc/sudoers.d/{{ user.name }}"
  tags:
    - user
    - sudo

# These paths are referred all throughout other roles
# so take care to modify
- name: Create user directories.
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}"
    - "{{ user.dirs.home }}/{{ user.dirs.bin }}"
    - "{{ user.dirs.home }}/{{ user.dirs.lib }}"
    - "{{ user.dirs.home }}/{{ user.dirs.share }}"
    - "{{ user.dirs.home }}/{{ user.dirs.desktop }}"
    - "{{ user.dirs.home }}/{{ user.dirs.download }}"
    - "{{ user.dirs.home }}/{{ user.dirs.templates }}"
    - "{{ user.dirs.home }}/{{ user.dirs.public }}"
    - "{{ user.dirs.home }}/{{ user.dirs.documents }}"
    - "{{ user.dirs.home }}/{{ user.dirs.music }}"
    - "{{ user.dirs.home }}/{{ user.dirs.pictures }}"
    - "{{ user.dirs.home }}/{{ user.dirs.videos }}"
    - "{{ user.dirs.home }}/{{ user.dirs.images }}"
    - "{{ user.dirs.home }}/{{ user.dirs.screenshots }}"
    - "{{ user.dirs.home }}/{{ user.dirs.wallpapers }}"
    - "{{ user.dirs.home }}/{{ user.dirs.workspace }}"
    - "{{ user.dirs.home }}/{{ user.dirs.share }}/applications"
  tags:
    - user
    - directory

- name: Copy configuration files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: user-dirs.dirs
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/user-dirs.dirs"
  tags:
    - user
    - config

- name: Copy environment variable file.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: 80-user-local-bin.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d/80-user-local-bin.conf"
  notify:
    - compile session
  tags:
    - user
    - config
