---
####################################################################################################
#
# Create the account that will use this computer as a user.
#
####################################################################################################
- name: Create normal user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ ma_user.name }}"
    password: "{{ ma_user.password }}"
    home: "{{ ma_user.dirs.home }}"
    shell: /bin/bash
    append: yes
    groups: 'systemd-journal'
  tags:
    - user

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Give this user sudo access for a few commands.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    # can only use shutdown and reboot
    content: "{{ ma_user.name }} ALL=(root) NOPASSWD: {{ ma_user.commands|join(',') }}\n"
    dest: "/etc/sudoers.d/{{ ma_user.name }}"
  tags:
    - user
    - sudo

# These paths are referred all throughout other roles
# so take care to modify
- name: Create user directories.
  become: yes
  become_user: root
  become_method: sudo
  file: 
    path: "{{ item }}"
    state: directory
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.bin }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.lib }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.share }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.desktop }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.download }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.templates }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.public }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.documents }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.music }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.pictures }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.videos }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.images }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.screenshots }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.wallpapers }}"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.workspace }}"
    # systemd user service directory
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/systemd/user"
  tags:
    - user
    - directory

- name: Copy configuration files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - src: user-dirs.dirs
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/user-dirs.dirs"
    - src: .profile
      dest: ~/.profile
  tags:
    - user
    - config
