---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for lxqt-session.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    # it is also installed in ma_de role
    - lxqt-session
  tags:
    - session
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create session config and autostart directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d"
    - "{{ user.dirs.home }}/{{ user.dirs.config }}/autostart"
  tags:
    - session
    - config

- name: Copy header and footer for session config file.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
    mode: 0755
  with_items:
    - src: 00-header.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d/00-header.conf"
    - src: 99-footer.conf
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/lxqt/session.conf.d/99-footer.conf"
  notify:
    - compile session
  tags:
    - session
    - config
