---
####################################################################################################
#
# Handlers for xorg
#
####################################################################################################
- name: compile xresources
  become: yes
  become_user: root
  become_method: sudo
  assemble:
    src: "{{ user.dirs.home }}/{{ user.dirs.config }}/xresources"
    dest: "{{ user.dirs.home }}/.Xresources"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  tags:
    - xserver
    - config
