---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for bspwm.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - bspwm
    - sxhkd
  tags:
    - wm
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create required directory for bspwm and sxkhd config
  become: yes
  become_user: root
  become_method: sudo
  file: 
    path: "{{ item }}"
    state: directory
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd"
  tags:
    - wm
    - config
    - directory

- name: Copy bspwmrc and sxkhdrc config files.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
    mode: 0755
  with_items:
    - src: bspwmrc
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm/bspwmrc"
    - src: sxhkdrc
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc"
  tags:
    - wm
    - config
