---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for bspwm.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - bspwm
  tags:
    - wm
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create required directory for bspwm config
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm"
  tags:
    - wm
    - config
    - directory

- name: Copy bspwm config files.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
    mode: 0755
  with_items:
    - src: bspwmrc
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm/bspwmrc"
  tags:
    - wm
    - config

- name: Copy bspwm hotkeys.
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ ma_user.name }}"
    owner: "{{ ma_user.name }}"
    mode: 0755
  with_items:
    - src: 10-wm
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc.d/10-wm"
  notify:
    - compile hotkeys
  tags:
    - wm
    - config
