---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for bspwm.
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: '{{ 12*60*60|int }}'
  with_items:
    - bspwm
    - sxhkd
    - dbus-user-session
  tags:
    - wm
    - package

####################################################################################################
#
# Configuration
#
####################################################################################################
- name: Create required directory for bspwm and sxkhd config
  file: path="{{ item }}" state=directory
  become: yes
  become_user: "{{ ma_user.name }}"
  become_method: sudo
  with_items:
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm"
    - "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd"
  tags:
    - wm
    - config
    - directory

- name: Copy bspwmrc and sxkhdrc config files.
  become: yes
  become_user: "{{ ma_user.name }}"
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: bspwmrc
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/bspwm/bspwmrc"
    - src: sxhkdrc
      dest: "{{ ma_user.dirs.home }}/{{ ma_user.dirs.config }}/sxhkd/sxhkdrc"
  tags:
    - wm
    - config
