---
####################################################################################################
#
# Installation
#
####################################################################################################
- name: Install required packages for automounting.
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - udisks2
      - udiskie
    state: latest
  when: "not (ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'virtualbox')"
  tags:
    - automount
    - package

####################################################################################################
#
# Autostart
#
####################################################################################################
- name: Copy desktop file for autostart.
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ user.name }}"
    owner: "{{ user.name }}"
  with_items:
    - src: udiskie.desktop
      dest: "{{ user.dirs.home }}/{{ user.dirs.config }}/autostart/udiskie.desktop"
  when: "not (ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'virtualbox')"
  tags:
    - automount
    - autostart

